# Generated by Django 4.0.1 on 2022-01-12 18:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authuser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='class_name')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('remark', models.CharField(max_length=100, verbose_name='remark')),
                ('is_local', models.BooleanField(verbose_name='is_local')),
                ('status', models.BooleanField(verbose_name='status')),
                ('author_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'db_table': 'scul_classes',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='country_name')),
                ('author_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'scul_countries',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('trans_type', models.PositiveSmallIntegerField(choices=[(0, 'from-class-to-class'), (1, 'graduate'), (2, 'another-school')], default=0, help_text='transaction_type', verbose_name='transaction_type')),
                ('author_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cls_fromtrans', to='scul.classroom', verbose_name='classroom')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='st_trans', to='authuser.student', verbose_name='student')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cls_totrans', to='scul.classroom', verbose_name='classroom')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'db_table': 'scul_trans',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='term_name')),
                ('start_date', models.DateField(verbose_name='term_start_date')),
                ('end_date', models.DateField(verbose_name='term_end_date')),
                ('author_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'db_table': 'scul_terms',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='subject_name')),
                ('short', models.CharField(max_length=5, verbose_name='remark')),
                ('author_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'scul_subjects',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='session_name')),
                ('author_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='c_sess', to='scul.classroom', verbose_name='classroom')),
                ('teacher_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tch_sess', to='authuser.teacher', verbose_name='teacher')),
                ('term_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ter_sess', to='scul.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'db_table': 'scul_sessions',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name_of_school')),
                ('instit', models.CharField(max_length=255, verbose_name='educational_institution')),
                ('region', models.CharField(max_length=255, verbose_name='region_of_school')),
                ('author_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('country_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cou_schools', to='scul.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'scul_schools',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('score', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='subject_name')),
                ('score_type', models.PositiveSmallIntegerField(choices=[(0, 'daily'), (1, 'test'), (2, 'quarter'), (3, 'exam'), (4, 'annual')], default=0, help_text='scor_type', verbose_name='score_type')),
                ('author_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stu_scores', to='authuser.student', verbose_name='student')),
                ('subject_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_scores', to='scul.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'db_table': 'scul_journals',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='school_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sch_classes', to='scul.school', verbose_name='school'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('author_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stu_attends', to='authuser.student', verbose_name='student')),
                ('subject_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_attends', to='scul.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'scul_attends',
            },
        ),
    ]
